GEMINI_API_KEY_VOICE = "AIzaSyDDrp1kfopf77oxq-g8jBBYWsFbuMNrlr8"
DEEPSEEK_API_KEY = "sk-5d93cd7ed9754d20b15920ed2df8e740"
SUPABASE_URL = "https://lkjglgforpneflgoihxs.supabase.co"
SUPABASE_KEY = "sb_publishable_P3FO3UHaL8_l9JjPUtRdkw_luCvNSsj"

[passwords]
admin = "iloveljh"
friend1 = "666666"
friend2 = "88888888"